// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bwmarrin/discordgo"
	"github.com/techstart35/battle-bot/app"
	"github.com/techstart35/battle-bot/gateway/persistence/store/battle"
)

// Injectors from wire.go:

// アプリケーションサービスの作成
func InitApp(session *discordgo.Session) (*app.App, error) {
	repository, err := battle.NewRepository()
	if err != nil {
		return nil, err
	}
	query, err := battle.NewQuery()
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(repository, query, session)
	return appApp, nil
}

// クエリの作成
func InitQuery() (*battle.Query, error) {
	query, err := battle.NewQuery()
	if err != nil {
		return nil, err
	}
	return query, nil
}
